# Build Stage
FROM rust:1.56 as builder
WORKDIR /usr/src

COPY ./reqreply/Cargo.toml ./reqreply/Cargo.lock ./
RUN mkdir src/
RUN cargo build --bin replier

COPY ./reqreply/src ./src
RUN cargo build --bin replier

# Runtime Stage
FROM debian:buster-slim as runtime
COPY --from=builder /usr/src/target/debug/replier /usr/local/bin/
CMD ["replier"]
